import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/ui/theme-provider';
import './globals.css';
import QueryProvider from '@/components/provider/query-provider';
import { Toaster } from 'sonner';
export const metadata: Metadata = {
  title: 'SIKERS RSAM',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange>
          <QueryProvider>{children}</QueryProvider>
          <Toaster position="top-center" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
